export const colors = {
    youtube:
        {
            likesColor:{
                color:"#FF0935"
            },
            arrowButtonsColor:{
                background:"#FF0935"
            },
            priceColor:{
                color:"#FF0935"
            },
            timeColor:{
                color:"#FF0935"
            },


        },
    instagram:
        {
            likesColor:{
                color:"#285FFF"
            },
            arrowButtonsColor:{
                background:"linear-gradient(88.32deg, #FEDA7D -15.05%, #D62F81 34.34%, #5E0DFF 108.12%)"
            },
            priceColor:{
                color:"#285FFF"
            },
            timeColor:{
                color:"#285FFF"
            }

        },
    tiktok:
        {
            likesColor:{
                color:"#03E6F4"
            },
            arrowButtonsColor:{
                background:"#03E6F4"
            },
            priceColor:{
                color:"#FF0935"
            },
            timeColor:{
                color:"#FF0935"
            }

        },
    twitter:{
        likesColor:{
            color:"#02C6F8"
        },
        arrowButtonsColor:{
            background:"#02C6F8"
        },
        priceColor:{
            color:"#02C6F8"
        },
        timeColor:{
            color:"#02C6F8"
        }
    },
    spotify:{
        likesColor:{
            color:"#54DE80"
        },
        arrowButtonsColor:{
            background:"#54DE80"
        },
        priceColor:{
            color:"#54DE80"
        },
        timeColor:{
            color:"#54DE80"
        }
    },
    vk:{
        likesColor:{
            color:"#7BA8CB"
        },
        arrowButtonsColor:{
            background:"#7BA8CB"
        },
        priceColor:{
            color:"#7BA8CB"
        },
        timeColor:{
            color:"#7BA8CB"
        }
    },
    facebook:{
        likesColor:{
            color:"#176BE8"
        },
        arrowButtonsColor:{
            background:"#176BE8"
        },
        priceColor:{
            color:"#176BE8"
        },
        timeColor:{
            color:"#176BE8"
        }
    }
}
